Squashed 'gc/' changes from 8b2a98209..cef9cbed8
cef9cbed8 [7.6.10]
79b751979 Update ChangeLog file (set v7.4.16 release date)
735ae6d70 Update ChangeLog file (set v7.2m release date)
872b28f01 Update ChangeLog file (v7.6 changes)
8d4d442cc Update ChangeLog file (v7.2 - v7.4 changes only)
25f39e1c5 Travis CI: Do not run cppcheck twice for cord, tests, tools source files
6895760d7 Refine HIDE_POINTER documentation for the case of the leak-finding mode
4d5873a00 Travis CI: Fix odr-violation reported by ASan when compiled as C++
5892b02b7 Fix a deadlock in write_fault_handler if AO_or is emulated (a cherry-pick of commit 8fd44dd2 from 'release-8_0')
68750041b Fix 'set_pht_entry_from_index_concurrent value is unknown' cppcheck warning (a cherry-pick of commit 1c82c8b3 from 'release-8_0')
8e451432e Fix lock assertion violation in get_index if GC_ALWAYS_MULTITHREADED (back-port of commit 90f50b5f0 from 'release-8_0')
a8a26edfc Prevent double inclusion of javaxfc.h and private/specific.h (a cherry-pick of commit 80f25f12 from 'release-8_0')
73b0a4617 Travis CI: Use latest (1.85) release version of cppcheck
e574884ba Travis CI: Execute cppcheck without sudo and -U long (a cherry-pick of commit c7204852 from 'release-8_0')
b277e3348 Travis CI: Test with FIND_LEAK (a cherry-pick of commit ba94c62a from 'release-8_0')
38e0cee5b New macro to suppress printing of leaked objects
06ee65e4f Eliminate 'casting signed to bigger unsigned int' CSA warning (a cherry-pick of commit ed3d74bf from 'release-8_0')
ce8444e2d Reduce scope of local variables in GC_remove_all_threads_but_me
adbb95cc5 Eliminate 'non-virtual destructor for class with inheritors' CSA warning
34481ceea Fix tests linkage with internal atomic_ops.o
4090c0aab Update AUTHORS file (add Fabrice Fontaine)
57650bc9b Fix linkage with a system libatomic_ops shared library (a cherry-pick of commit 1b49ae99 from 'release-8_0')
754b34ee1 Fix 'too wide non-owner permissions are set for resource' code defect
79e703647 Fix 'collecting from unknown thread' abort in leak-finding mode for Win32 (a cherry-pick of commit 3f7a8b80 from 'release-8_0')
8307cb71b Add paths to filenames mentioned in the copyright section in README
67f5553e1 Update AUTHORS file
236b9ad2e Update documentation about arm64 ABI in gcconfig.h (fix of commit b399b13b9)
af4bde3e6 Guard against potential buffer overflow in CORD_next and CORD_pos_fetch (a cherry-pick of commit e4fcf92a from 'release-8_0')
b1a28293e Fix test_cpp assertion violation in find-leak mode
e59f5cc07 Fix hbp overflow in GC_install_counts (a cherry-pick of commits 6a32bb4, 36a6d79 from 'master')
e773ef74d Fix GC_register_disclaim_proc for leak-finding mode (a cherry-pick of commit 9d8628c9 from 'release-8_0')
1a91e4c4f Fix marks and hb_n_marks consistency when disclaim returns true
94e1e96f9 .gitignore: Ignore disclaim_weakmap_test executable file
16cbc85da Update ChangeLog file (v7.6 changes)
00e91c698 Update ChangeLog file (v7.2 - v7.4 changes only) (a cherry-pick of commit 4bcd0c33 from 'release-7_4')
eed796d6d Fix memory allocation on GCF (Linux/x64) (back-port of commit 32704bf8a from 'master')
8089d0630 Call real pthread_sigmask instead of its wrapper in start_mark_threads (fix of commit 95947bdc5)
27e1e86b2 Use AO_or in async_set_pht_entry_from_index if available (back-port of commit 13af9c5ab from 'release-8_0')
26e9e59e6 Fix concurrent bitmap update in GC_dirty (back-port of commit 815dde366 from 'release-8_0')
576209980 Test marking of finalizer closure object in disclaim_test (a cherry-pick of commit a917ba1fc from 'release-8_0')
54b9dae65 Fix unneeded end_stubborn_change in disclaim_test (a cherry-pick of commit 71948aeae from 'release-8_0')
1cfe03210 Refine documentation in gc_disclaim.h (a cherry-pick of commits 8ce6ef666, 4158701ae from 'master')
25e85ca4d Fix marking of finalizer closure object (a cherry-pick of commits 21312a008, ea9d6dd6a from 'master')
b75f8d91b Fix comment typo in CMakeLists.txt
476b77ea3 Fix GC_VSNPRINTF in cordprnt for DJGPP and MS VC for WinCE (fix of commit c10a1d900)
5a52aa739 Fix missing curses.h in cord/de when compiling manually (MS VC, MinGW)
d2e20dc4d Fix comment typos in backgraph.c, de.c, gcconfig.h
35a2b3a07 Update AUTHORS file (add Demyan Kimitsa)
c1ca63a30 Fix start_world not resuming all threads on Darwin
2ab0fbd43 Fix indentation of 'define GC_DATAEND' in gc.h (fix of commit 4e24d219d)
d3d800c40 Travis CI: Put GNU S/W download base URL in a dedicated variable (cherry-pick of commits a9690ac, de24da8 from 'master')
4a67c8d07 Fix delete operator redirection if gc_cpp is built as .dll (Cygwin, MinGW) (back-port of commit 5e51e8d from 'master')
e76f302bf Fix 'undefined reference to GC_incremental' linker error in pthread_start (fix of commit 73d30d2)
c1d9af84e Use include gc.h with the angle brackets in the man page synopsis

git-subtree-dir: gc
git-subtree-split: cef9cbed83f2b5101d4e65ca0f158600d26cbd34