Squashed 'gc/' changes from 3e8ca9e8d..d3dede3ce
d3dede3ce [8.0.4]
78c7aea27 Update ChangeLog file (v8.0 changes)
3fd9a4804 Update ChangeLog file (set v7.4.18 release date)
31bb95891 Update ChangeLog file (set v7.2n release date)
d49688406 Avoid potential race in hb_sz access between realloc and reclaim_block
7c5992de5 Fix 'duplicate symbol' error for tests using multiple static libs (OS X)
e6a30a35c Avoid a full GC when growing finalizer tables if in incremental mode (a cherry-pick of commits 6e0590ef1, c23bad10a from 'master')
6f46a27de .gitignore: Ignore /out folder
011e159e9 Update ChangeLog file (v8.0 changes)
002a77532 Update ChangeLog file (v7.6 changes) (a cherry-pick of commit 1d3beb1c from 'release-7_6')
7b178053b Update ChangeLog file (v7.2 - v7.4 changes only) (a cherry-pick of commit dd4558f0 from 'release-7_4')
4e79c357e Avoid unexpected heap growth in gctest caused by GC_disable (fix of commit 8fc1ebf6d)
88664f9b7 AppVeyor CI: Fix 'no source or binary dir provided' cmake error
5b5ae3036 Fix thread_info() count argument value (OS X)
7744b5d5d Fix 'wrong __data_start/_end pair' error on Android (a cherry-pick of commit e1ef3b22 from 'master')
fcb9eab7e Fix GetThreadContext stale register values use if WoW64 (Win32)
30990efee Fix 'undefined reference to __data_start' linker error (Android/aarch64)
ee34d55df Workaround 'wrong __data_start/_end' if __end__ is incorrect (Android)
c9381cc6d Fix 'unexpected mark stack overflow' abort in push_all_stack
1358802b8 Travis CI: Test with -D BSD_TIME passed to CFLAGS
74e4c4aa5 Ensure result of every variant of MS_TIME_DIFF has unsigned long type (code refactoring)
f6d516fed Fix BSD_TIME variant of MS_TIME_DIFF for the case of a.tv_usec < b.tv_usec (fix of commit 6b2796b69)
203cc13db Fix invalid initializer of CLOCK_TYPE variables if BSD_TIME (fix of commits 7e59301c1, 06ecaefca)
e3502c3bf Support de_win.c compilation by Makefile.direct (cord/de)
de25c7374 Avoid test.o rebuild on tests folder timestamp change (Makefile.direct)

git-subtree-dir: gc
git-subtree-split: d3dede3ce4462cd82a15f161af797ca51654546a