Squashed 'gc/libatomic_ops/' changes from 8d98e2811..76ffb3b87
76ffb3b87 Bump libatomic_ops version to 7.6.6
a8b806d4d Update ChangeLog file (v7.6 changes)
326793bf6 Update copyright information in README and some header files
3e00e6b4f Travis CI: Upgrade clang-4.0 to clang-5.0, and gcc-5 to gcc-8 (cherry-pick of commits c475050, bc42d68 from 'master')
1ff4bd2d4 Travis CI: Test with gcc-7/x86_64 and -march=native flag on Linux
ecb768f43 COPYING: sync with FSF's gpl-2.0.txt
7d85eae97 Fix comments style in configure.ac and Makefile.am (cherry-pick of commit d2864b5 from 'master')
1927f18eb Fix a typo in the overview section of README (fix of commit 147988d9)
26bec1542 Fix 'undefined reference to __atomic_load/store/cas_16' error (gcc-7/x64)

git-subtree-dir: gc/libatomic_ops
git-subtree-split: 76ffb3b87946e4c372d112d8d00786632deab934