Squashed 'gc/' changes from 4d1a516e6..0125d569a
0125d569a [7.6.6]
191179d8a Update ChangeLog file (v7.6 changes only)
78a3fb068 Eliminate 'boolean result used in bitwise operation' cppcheck warning
5891f0c33 Workaround gctest hang on kFreeBSD if thread-local allocations are on (back-port of commit 228e9b2 from 'master')
61a65eb73 Update ChangeLog file (add gc-7.4.12 release date)
5aaa9e327 Update ChangeLog file (v7.2 - v7.4 changes only)
9a46da7e7 Fix 'pointer of type void* used in arithmetic' compiler warning in dbg_mlc (fix of commit 8f63e5b)
2b8cd0b89 Fix data race during apply_to_each_object(reset_back_edge) (back-port of commit d7ea0b1 from 'master')
3a565c143 Support threads for DragonFly in configure (back-port of commit 19c81d80 from 'master')
47ca7611e Workaround sem_wait failure in pthread_create on Haiku
1d9c1e437 Workaround Haiku pthread_join failure in subthreadcreate_test
1761adf6c Update AUTHORS file (add Calvin Hill)
f6167681d Initial support of Haiku/amd64 (back-port of commits 847927f, 2396ce1 from 'master')
8f63e5b30 Fix the collector hang when it is configured with --enable-gc-debug (back-port of commits d6ccabe, 2e8c66c from 'master')
7881f44ef Eliminate TSan warning about data race when accessing GC_debugging_started
b6b7dbb9d Fix unbounded heap growth in case of intensive disappearing links usage (back-port of commits b04b346, 46e7ec2 from 'master')
118e7689a Fix null dereference in print_callers on backtrace_symbols failure
4b9fd6bbd Fix null pointer dereference in get_private_path_and_zero_file (Symbian) (back-port of commit 9d019e2e from 'master')
83dd5411e Fix missing SIGBUS handler setup for kFreeBSD
96df30682 Define GC_FREEBSD_THREADS and GC_ADD_CALLER macros for kFreeBSD (back-port of commit 5700d205 from 'master')
9c86cda70 Eliminate 'there is pointer arithmetic with NULL' cppcheck warning
3c330f9af Explicitly unblock GC signals on GC initialization
3f5bb0a73 Fix thread_suspend fail for threads registered from key destructor (OS X)
da804cfea Fix assertion violation in DllMain of win32_threads
b5bc2819d Fix 'scope of var can be reduced' cppcheck err in enqueue_all_finalizers (back-port of commit b82af3a3 from 'master')
ffd52f264 Fix comment for debug_generic_malloc_inner[_ignore_off_page] (fix of commit 38965f279)
12d1a4d3d Update ChangeLog file (v7.6 changes only)
359b76670 Update ChangeLog file (v7.2 - v7.4 changes only) (a cherry-pick of commit 08a2e0ba from 'release-7_4')
f04a873c1 Fix missing GC_generic_malloc_words_small implementation in new_gc_alloc.h
560296479 Fix include gc_gcj.h in thread_local_alloc.c (back-port of commit 60d9632a from 'master')
e0a1e81eb Remove API symbols renaming in WCC_MAKEFILE
1288c9d73 Travis CI: Output content of threadkey_test.log
d6e2b8ba9 Fix typo in AIX macro name
4e625c93c Fix dbg_mlc.c/o file name in documentation
4a13abcc5 Fix missing new-line in GC_INFOLOG_PRINTF call in ABORT_ARG<n>
9c4adbc3c Update AUTHORS file (add Natanael Copa)
f8a6bd73b Fix gctest with musl libc on s390x
e7401008e Fix type of local variables receiving result of PHT_HASH (back-port of commit 037991eb from 'master')
0b7bad876 Fix man section number (3)
bb808fcd7 Fix arguments delimiter in pcr_interface.c (PCR)
045488771 Update AUTHORS file (add Jay Krell)
cb4e5257d Fix typo in comment in specific.h
d0915ae1c Fix 'undefined reference to __builtin_unwind_init' linker error (ArmCC) (part of commit 9379c66 from Unity-Technologies/bdwgc)
e225985a4 Workaround 'address of auto-variable returned' cppcheck error (back-port of commit b51bdee1 from 'master')

git-subtree-dir: gc
git-subtree-split: 0125d569a533cab24b492db5854b5486969cb28d